users = []

[locales]
keyboard_layout = "de_CH-latin1"
locale_language = "de_CH.UTF-8"
locale_encoding = "UTF-8"

[mirrors]
regions = ["Switzerland            CH    26"]
optional_repos = [
    "multilib",
    "AUR",
]
aur_helper = "yay"
custom_servers = []
custom_repos = []

[disks]
mode = "Best-effort partition layout"
selected_device = "/dev/sdb"
selected_device_model = "ST2000DM006-2DM164"
selected_device_devtype = "disk"
selected_device_size = "1.8 TiB"
selected_device_freespace = "1.8 TiB"
selected_device_sector_size = "512/4096 B"
selected_device_read_only = false
label = "gpt"
wipe = true
align = "1MiB"
partitions = []

[disk_encryption]
encryption_type = "None"

[swap]
enabled = true

[bootloader]
kind = "grub"

[system]
hostname = "Archlinux"
root_password_hash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
automatic_time_sync = true
timezone = "Europe/Zurich"

[unified_kernel_images]
enabled = false

[kernels]
selected = ["linux"]

[audio]
kind = "pipewire"

[experience]
mode = "Minimal"
desktop_envs = []
server_types = []
xorg_types = []
login_manager_user_set = false
graphic_drivers = []

[experience.desktop_env_packages]

[experience.server_packages]

[experience.xorg_packages]

[network]
mode = "NetworkManager"

[[additional_packages]]
repo = ""
name = "alacritty"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "fish"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "firefox"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "neovim"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "stow"
version = ""
description = "Selected from package groups"
