[locales]
keyboard_layout = "de_CH-latin1"
locale_language = "de_CH.UTF-8"
locale_encoding = "UTF-8"

[mirrors]
regions = ["Switzerland            CH    26"]
optional_repos = ["multilib"]
custom_servers = []
custom_repos = []

[disks]
mode = "Manual Partitioning"
selected_device = "/dev/sdb"
selected_device_model = "ST2000DM006-2DM164"
selected_device_devtype = "disk"
selected_device_size = "1.8 TiB"
selected_device_freespace = "1.8 TiB"
selected_device_sector_size = "512/4096 B"
selected_device_read_only = false
label = "gpt"
wipe = true
align = "1MiB"

[[disks.partitions]]
name = "/dev/sdb"
role = "BOOT"
fs = "fat32"
start = "0"
size = "1073741824"
flags = []
mountpoint = "/boot"

[[disks.partitions]]
name = "/dev/sdb"
role = "SWAP"
fs = "linux-swap"
start = "1073741824"
size = "4294967296"
flags = []

[[disks.partitions]]
name = "/dev/sdb"
role = "ROOT"
fs = "btrfs"
start = "5368709120"
size = "1995012308992"
flags = []
mountpoint = "/"

[disk_encryption]
encryption_type = "None"

[swap]
enabled = true

[bootloader]
kind = "grub"

[system]
hostname = "Archlinux"
root_password_hash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
automatic_time_sync = true
timezone = "Europe/Zurich"

[unified_kernel_images]
enabled = false

[kernels]
selected = ["linux"]

[audio]
kind = "pipewire"

[experience]
mode = "Desktop"
desktop_envs = ["KDE Plasma"]
server_types = []
xorg_types = []
login_manager = "sddm"
login_manager_user_set = false
graphic_drivers = [
    "intel-media-driver",
    "libva-intel-driver",
    "mesa",
    "vulkan-intel",
    "vulkan-nouveau",
    "vulkan-radeon",
    "xf86-video-amdgpu",
    "xf86-video-ati",
    "xf86-video-nouveau",
    "xorg-server",
    "xorg-xinit",
]

[experience.desktop_env_packages]
"KDE Plasma" = [
    "ark",
    "dolphin",
    "htop",
    "iwd",
    "kate",
    "konsole",
    "nano",
    "openssh",
    "plasma-meta",
    "plasma-workspace",
    "smartmontools",
    "vim",
    "wget",
    "wireless_tools",
    "wpa_supplicant",
    "xdg-utils",
]

[experience.server_packages]

[experience.xorg_packages]

[[users]]
username = "firstpick"
password_hash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
is_sudo = true

[network]
mode = "NetworkManager"

[[additional_packages]]
repo = "extra"
name = "kitty"
version = "0.42.2-1"
description = "A modern, hackable, featureful, OpenGL-based terminal emulator"

[[additional_packages]]
repo = "extra"
name = "fish"
version = "4.0.6-1"
description = "Smart and user friendly shell intended mostly for interactive use"

[[additional_packages]]
repo = "extra"
name = "firefox"
version = "143.0-1"
description = "Fast, Private & Safe Web Browser"

[[additional_packages]]
repo = "extra"
name = "neovim"
version = "0.11.4-1"
description = "Fork of Vim aiming to improve user experience, plugins, and GUIs"

[[additional_packages]]
repo = "extra"
name = "stow"
version = "2.4.1-1"
description = "Manage installation of multiple softwares in the same directory tree"

[[additional_packages]]
repo = "core"
name = "nano"
version = "8.6-1"
description = "Pico editor clone with enhancements"

[[additional_packages]]
repo = ""
name = "vim"
version = ""
description = "Selected from package groups"
