[locales]
keyboard_layout = "us"
locale_language = "en_US.UTF-8"
locale_encoding = "UTF-8"

[mirrors]
regions = ["United States          US   186"]
optional_repos = [
    "multilib",
    "AUR",
]
aur_helper = "paru"
custom_servers = []
custom_repos = []

[disks]
mode = "Best-effort partition layout"
selected_device = "/dev/sda"
selected_device_model = "Virtual Disk"
selected_device_devtype = "disk"
selected_device_size = "64.0 GiB"
selected_device_freespace = "64.0 GiB"
selected_device_sector_size = "512 B"
selected_device_read_only = false
label = "gpt"
wipe = true
align = "1MiB"
partitions = []

[disk_encryption]
encryption_type = "None"

[swap]
enabled = true

[bootloader]
kind = "grub"

[system]
hostname = "Archlinux"
root_password_hash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
automatic_time_sync = true
timezone = "Europe/London"

[unified_kernel_images]
enabled = false

[kernels]
selected = ["linux"]

[audio]
kind = "pipewire"

[experience]
mode = "Desktop"
desktop_envs = ["KDE Plasma"]
server_types = []
xorg_types = []
login_manager = "sddm"
login_manager_user_set = false
graphic_drivers = [
    "intel-media-driver",
    "libva-intel-driver",
    "mesa",
    "vulkan-intel",
    "vulkan-nouveau",
    "vulkan-radeon",
    "xf86-video-amdgpu",
    "xf86-video-ati",
    "xf86-video-nouveau",
    "xorg-server",
    "xorg-xinit",
]

[experience.desktop_env_packages]
"KDE Plasma" = [
    "ark",
    "dolphin",
    "htop",
    "iwd",
    "kate",
    "konsole",
    "nano",
    "openssh",
    "plasma-meta",
    "plasma-workspace",
    "smartmontools",
    "vim",
    "wget",
    "wireless_tools",
    "wpa_supplicant",
    "xdg-utils",
]

[experience.server_packages]

[experience.xorg_packages]

[[users]]
username = "firstpick"
password_hash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
is_sudo = true

[network]
mode = "NetworkManager"

[[additional_packages]]
repo = ""
name = "alacritty"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "fish"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "firefox"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "neovim"
version = ""
description = "Selected from package groups"

[[additional_packages]]
repo = ""
name = "stow"
version = ""
description = "Selected from package groups"
